### ISSUE TITLE
`Result._read_stdout_or_stderr` sometimes wedges in an infinite loop

### ISSUE THREAD

**Issue by richvdh** [julienc91/pystassh#6]
On my system, it appears that sometimes a channel gets closed before the EOF is read, so that `ssh_channel_read` returns -1.

When this happens, `Result._read_stdout_or_stderr` gets stuck in an infinite loop, because the condition at https://github.com/julienc91/pystassh/blob/1.2.1/pystassh/result.py#L34 is waiting for `ssh_channel_read` to return 0.

**Comment by richvdh** [comment]
I applied a patch locally to replace the condition with `while count > 0`, which appears to work fine, though I'm not sure if there is a better way to solve it.

**Comment by julienc91** [comment]
@richvdh Hi Richard! Do you have a way to reproduce this bug consistently?

**Comment by julienc91** [comment]
I found in the [documentation](https://api.libssh.org/stable/group__libssh__channel.html#gac92381c4c5d4a7eab35f6e84686f033d) that `ssh_channel_read` could return `SSH_ERROR`, which is indeed -1. In think your fix is correct :slightly_smiling_face:

**Comment by julienc91** [comment]
Fixed in [1.2.2](https://github.com/julienc91/pystassh/releases/tag/1.2.2)

**Comment by richvdh** [comment]
Thanks for fixing this so quickly!
